# Use an official Python runtime as the parent image
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install required libraries
RUN pip install --no-cache-dir requests redis tabulate

# Run the script when the container launches
CMD ["python", "./pokemon_sim.py"]
